### ISSUE TITLE
Getting error when use the search_top and search_all

### ISSUE THREAD

**Issue by thawancomt** [anishomsy/apkpure#1]
the soup object is returning this HTML 
![image](https://github.com/anishomsy/apkpure/assets/131563700/6abc9889-95a1-4a16-a824-b101ffdb0b4f)

Probably a 403 code... maybe there is some authentication necessary?
of course, after printing the status code, Im getting a 403 status code

**Comment by anishomsy** [comment]
hey, can you let me know what package you were trying to find. Also I updated the package, update your version, maybe that would fix your problem.

**Comment by thawancomt** [comment]
Any search result in 403 status code, the latest version.
The root is that the request to apkpure website return 403 code, then any other functionality of the script will fail
![image](https://github.com/anishomsy/apkpure/assets/131563700/7d1370ae-ba15-4920-8d12-20a04a837913)

**Comment by anishomsy** [comment]
Try updating the package, It should be fixed now, if it isn't let me know.

**Comment by thawancomt** [comment]
Are you using some proxy or VPN? Let me know, cause the apkpure detect we are using an automatic system, then they block our request, so we need some way to bypassed it...if you are using some tweak, maybe should be it

**Comment by anishomsy** [comment]
> Are you using some proxy or VPN? Let me know, cause the apkpure detect we are using an automatic system, then they block our request, so we need some way to bypassed it...if you are using some tweak, maybe should be it

I guess to bypass cloudflare, I opened the website in the browser and downloaded a file. Can you try that first? Also I will check out your pr.
